CREATE DATABASE SPRING;    

USE SPRING;

SHOW TABLES;

CREATE TABLE TEST(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
EMAILID VARCHAR(255)
)

INSERT INTO TEST(NAME,EMAILID) VALUES ("STEVE SMITH","STEVE@GMAIL.COM");

INSERT INTO TEST(NAME,EMAILID) VALUES ("ROCK","ROCK@GMAIL.COM");

SELECT * FROM TEST